export const complexes = [
    {
        name: 'Park Vista',
        address: '1000 Peppermint Lane',
        addresscitystatezip: 'Crystal, MN 55422',
        city: 'Crystal',
        mgr: 'Leigh Nguyen',
        phone: '(612) 555-5513',
        units: '65',
        unittypes: ['Studio', '1 Bed/1 Bath', '2 Bed/1 Bath'],
        amenities: ['Secure Entry', 'Swimming Pool', 'In-Unit W/D', 'Picnic Area'],
        description: 'Experience the perfect blend of comfort and convenience at Park Vista. Nestled in the vibrant Crystal community, across the street from luscious park trails and endless outdoor activities, our charming community offers a lifestyle of peaceful relaxation, balanced with the convenience of having shopping, highways, and public transportation nearby as well. Enjoy the serenity of our parklike setting, relax by the swimming pool, or have a picnic in our comfortable outdoor area. Park Vista is an ideal place for those seeking a tranquil lifestyle within the city.',
        img: 'images/parkvista.jpg',
        alt: 'Park Vista'
    },
    {
        name: 'The Grange at Eden Prairie',
        address: '5512 La Grange Road',
        addresscitystatezip: 'Eden Prairie, MN 55344',
        city: 'Eden Prairie',
        mgr: 'Reese Majors',
        phone: '(612) 555-5511',
        units: '600',
        unittypes: ['1 Bed/1 Bath', '2 Bed/1 Bath', '2 Bed/2 Bath', '3 Bed/2 Bath'],
        amenities: ['Secure Entry', 'Swimming Pool', 'In-Unit W/D', 'Fitness Center', 'Heated Parking Garage', 'Picnic Area', 'Playground'],
        description: 'Welcome to The Grange at Eden Prairie, where luxury meets convenience. With a range of spacious one, two, and three-bedroom apartments, our community caters to your needs. Enjoy our top-tier amenities like a fitness center, heated parking garage, and a delightful playground for children. Whether you\'re swimming in our pool or enjoying a family picnic, The Grange is more than just a place to live, it\'s a lifestyle.',
        img: 'images/grange.jpg',
        alt: 'The Grange at Eden Prairie'
    },
    {
        name: 'Thomas Park Villas',
        address: '5500 Thomas Park Lane',
        addresscitystatezip: 'Minnetonka, MN 55305',
        city: 'Minnetonka',
        mgr: 'Leigh Nguyen',
        phone: '(612) 555-5513',
        units: '15',
        unittypes: ['2 Bed/1 Bath'],
        amenities: ['Secure Entry', 'Newly Renovated'],
        description: 'Discover the charm of Thomas Park Villas in Minnetonka, with newly-renovated cabinetry, granite countertops, and hardwood floors. Our exclusive community, featuring two-bedroom apartments, offers a secure and peaceful living experience. Perfect for those who appreciate a more intimate and refined lifestyle, Thomas Park Villas is your serene retreat in the heart of the city.',
        img: 'images/tpv.jpg',
        alt: 'Thomas Park Villas'
    },
    {
        name: 'Lake View Villas',
        address: '55 Lake View Lane',
        addresscitystatezip: 'Minnetonka, MN 55305',
        city: 'Minnetonka',
        mgr: 'Latifa Corey',
        phone: '(612) 555-5556',
        units: '16',
        unittypes: ['1 Bed/1 Bath', '2 Bed/1 Bath'],
        amenities: ['Secure Entry', 'In-Unit W/D'],
        description: 'Embrace the serene living at Lake View Villas, a quaint community with views of Lake Minnetonka. Offering one and two-bedroom apartments with secure entry and in-unit washer/dryers, our property is ideal for those seeking a blend of simplicity and modern amenities. Lake View Villas is your tranquil haven in the bustling city.',
        img: 'images/lvv.jpg',
        alt: 'Lake View Villas'
    },
    {
        name: 'The Flats at St. Louis Park',
        address: '1234 Mariette Avenue',
        addresscitystatezip: 'St. Louis Park, MN 55424',
        city: 'St. Louis Park',
        mgr: 'Leigh Nguyen',
        phone: '(612) 555-5513',
        units: '36',
        unittypes: ['2 Bed/1 Bath', '2 Bed/2 Bath'],
        amenities: ['Secure Entry', 'In-Unit W/D', 'Heated Parking Garage'],
        description: 'The Flats at St. Louis Park welcomes you to experience modern living in a friendly neighborhood. Our two-bedroom apartments, equipped with in-unit washer/dryers and a heated parking garage, provide both comfort and convenience. Situated in the heart of St. Louis Park, our property is perfect for those seeking a contemporary urban lifestyle.',
        img: 'images/flatsslp.jpg',
        alt: 'The Flats at St. Louis Park'
    },
    {
        name: 'City View Apartments',
        address: '4545 Andrus Court',
        addresscitystatezip: 'St. Louis Park, MN 55424',
        city: 'St. Louis Park',
        mgr: 'Kimberly Anton',
        phone: '(612) 555-5557',
        units: '130',
        unittypes: ['Studio', '1 Bed/1 Bath', '2 Bed/1 Bath', '2 Bed/2 Bath'],
        amenities: ['Secure Entry', 'In-Unit W/D', 'Fitness Center'],
        description: 'City View Apartments in St. Louis Park is where urban living meets comfort. Offering a range of units from studios to two-bedroom apartments, all with in-unit washer/dryers, granite countertops, and hardwood floors, our community is designed for your lifestyle. With a state-of-the-art fitness center, City View is ideal for those who value wellness and convenience in the city.',
        img: 'images/cityview.jpg',
        alt: 'City View Apartments'
    },
    {
        name: 'Traverse at St. Louis Park',
        address: '702 Hypothetical Street',
        addresscitystatezip: 'St. Louis Park, MN 55426',
        city: 'St. Louis Park',
        mgr: 'Kimberly Anton',
        phone: '(612) 555-5557',
        units: '32',
        unittypes: ['2 Bed/1 Bath', '2 Bed/2 Bath'],
        amenities: ['Secure Entry', 'In-Unit W/D', 'Fitness Center', 'Picnic Area'],
        description: 'Traverse at St. Louis Park is a haven for those who seek a balanced lifestyle. Our two-bedroom apartments, complete with modern amenities like in-unit washer/dryers and a fitness center, cater to your comfort and health. The picnic area and parklike setting add a touch of nature to your urban living experience, making Traverse an ideal place to call home.',
        img: 'images/traverse.jpg',
        alt: 'Traverse at St. Louis Park'
    },
    {
        name: 'Maple Grove Park Villas',
        address: '10210 Elm Creek Park Lane',
        addresscitystatezip: 'Maple Grove, MN 55369',
        city: 'Maple Grove',
        mgr: 'Amanda Gellar',
        phone: '(612) 555-5555',
        units: '24',
        unittypes: ['2 Bed/1 Bath', '2 Bed/2 Bath'],
        amenities: ['Secure Entry', 'In-Unit W/D', 'Swimming Pool', 'Fitness Center', 'Picnic Area'],
        description: 'Welcome to Maple Grove Park Villas, where elegance meets modern living. Our two-bedroom apartments, equipped with in-unit washer/dryers and a range of amenities like a swimming pool and fitness center, are designed for your comfort. Enjoy our secure, tranquil community, set in the vibrant Maple Grove area, perfect for those seeking a sophisticated lifestyle.',
        img: 'images/mgpv.jpg',
        alt: 'Maple Grove Park Villas'
    },
    {
        name: 'Woodland Trails Square',
        address: '10101 Woodland Trails Court',
        addresscitystatezip: 'Elk River, MN 55330',
        city: 'Elk River',
        mgr: 'Amanda Gellar',
        phone: '(612) 555-5555',
        units: '16',
        unittypes: ['1 Bed/1 Bath', '2 Bed/1 Bath'],
        amenities: ['Secure Entry', 'Newly Renovated', 'Picnic Area'],
        description: 'Discover the charm of Woodland Trails Square in Elk River, a community that blends modern living with natural beauty. Our one and two-bedroom apartments, newly renovated with secure entry, offer a peaceful retreat from city life, with the convenience of downtown businesses and shopping close by. The picnic area amidst lush surroundings makes it a perfect place for relaxation and rejuvenation.',
        img: 'images/woodland.jpg',
        alt: 'Woodland Trails Square'
    }
];