export const propertiesData = [
    {
        name: "The Grange at Eden Prairie",
        address: "5512 La Grange Road",
        citystatezip: "Eden Prairie, MN 55344",
        zipCode: "55344",
        unit: "210",
        groundFloor: false,
        bedrooms: 2,
        bathrooms: 1,
        sqft: 1117,
        unitType: "apartment",
        rent: 1400,
        deposit: 1400,
        availableOn: "2024-02-01",
        amenities: ["Secure Entry", "Swimming Pool", "In-Unit W/D", "Fitness Center", "Heated Parking Garage", "Picnic Area", "Playground"],
        description: "Welcome to The Grange at Eden Prairie, where luxury meets convenience. With a range of spacious one, two, and three-bedroom apartments, our community caters to your needs. Enjoy our top-tier amenities like a fitness center, heated parking garage, and a delightful playground for children. Whether you're swimming in our pool or enjoying a family picnic, The Grange is more than just a place to live, it's a lifestyle.",
        img: "images/grange.jpg",
        alt: "The Grange at Eden Prairie",
        mgr: "Reese Majors",
        phone: "(612) 555-5511",
        email: "reesem@singhrealty.com",
        moreImgs: ["images/grange-living-room.jpg", "images/grange-kitchen.jpg", "images/grange-bedroom.jpg"],

        moreImgsAlt: ["The Grange at Eden Prairie - Exterior", "The Grange at Eden Prairie - Living Room", "The Grange at Eden Prairie - Kitchen", "The Grange at Eden Prairie - Bedroom"],
        mls: "400000"
    },
    {
        name: "The Grange at Eden Prairie",
        address: "5512 La Grange Road",
        citystatezip: "Eden Prairie, MN 55344",
        zipCode: "55344",
        unit: "417",
        groundFloor: false,
        bedrooms: 2,
        bathrooms: 2,
        sqft: 1250,
        unitType: "apartment",
        rent: 1650,
        deposit: 1650,
        availableOn: "2024-02-01",
        amenities: ["Secure Entry", "Swimming Pool", "In-Unit W/D", "Fitness Center", "Heated Parking Garage", "Picnic Area", "Playground"],
        description: "Welcome to The Grange at Eden Prairie, where luxury meets convenience. With a range of spacious one, two, and three-bedroom apartments, our community caters to your needs. Enjoy our top-tier amenities like a fitness center, heated parking garage, and a delightful playground for children. Whether you're swimming in our pool or enjoying a family picnic, The Grange is more than just a place to live, it's a lifestyle.",
        img: "images/grange.jpg",
        alt: "The Grange at Eden Prairie",
        mgr: "Reese Majors",
        phone: "(612) 555-5511",
        email: "reesem@singrealty.com",
        moreImgs: ["images/grange-kitchen.jpg", "images/grange-living-room.jpg", "images/grange-bedroom.jpg"],
        mls: "400001",
        moreImgsAlt: ["The Grange at Eden Prairie - Exterior", "The Grange at Eden Prairie - Living Room", "The Grange at Eden Prairie - Kitchen", "The Grange at Eden Prairie - Bedroom"]
    },
    {
        name: "Traverse at St. Louis Park",
        address: "702 Hypothetical Street",
        citystatezip: "St. Louis Park, MN 55426",
        zipCode: "55426",
        unit: "115",
        groundFloor: true,
        bedrooms: 2,
        bathrooms: 1,
        unitType: "apartment",
        rent: 1100,
        deposit: 1100,
        availableOn: "2024-03-01",
        amenities: ["Secure Entry", "In-Unit W/D", "Fitness Center", "Picnic Area"],
        description: "Traverse at St. Louis Park is a haven for those who seek a balanced lifestyle. Our two-bedroom apartments, complete with modern amenities like in-unit washer/dryers and a fitness center, cater to your comfort and health. The picnic area and parklike setting add a touch of nature to your urban living experience, making Traverse an ideal place to call home.",
        img: "images/traverse.jpg",
        alt: "Traverse at St. Louis Park",
        mgr: "Kimberly Anton",
        phone: "(612) 555-5557",
        email: "kimberlya@singhrealty.com",
        moreImgs: ["images/traverse-kitchen.jpg", "images/traverse-living-room.jpg", "images/traverse-bedroom.jpg"],
        mls: 400002,
        moreImgsAlt: ["Traverse at St. Louis Park - Exterior", "Traverse at St. Louis Park - Living Room", "Traverse at St. Louis Park - Kitchen", "Traverse at St. Louis Park - Bedroom"]
    },
    {
        name: "Single Family Home",
        address: "2617 Paul McCartney Court",
        citystatezip: "Elk River, MN 55330",
        zipCode: "55330",
        unit: "0",
        groundFloor: false,
        bedrooms: 4,
        bathrooms: 3,
        sqft: 3620,
        unitType: "house",
        rent: 2700,
        deposit: 5000,
        availableOn: "2024-04-01",
        amenities: ["In-Unit W/D", "Attached Garage", "Walkout Basement", "Fully-Finished Basement"],
        description: "Set on 2 acres with lush, mature landscaping, and close to highways and shopping, this newly-renovated home has all you need to enjoy the convenience of city living in a comfortable, parklike setting. Features a, out building, heated attached 2-car garage, hardwood floors throughout, and a fully finished walkout basement.",
        img: "images/house.jpg",
        alt: "2617 Paul McCartney Court",
        mgr: "Amanda Gellar",
        phone: "(612) 555-5555",
        email: "agellar@singhrealty.com",
        moreImgs: ["images/house-kitchen.jpg", "images/house-living-room.jpg", "images/house-bedroom.jpg"],
        mls: 400003,
        moreImgsAlt: ["2617 Paul McCartney Court - Exterior", "2617 Paul McCartney Court - Living Room", "2617 Paul McCartney Court - Kitchen", "2617 Paul McCartney Court - Bedroom"]
    }
]